{{ if and .Values.global.addons.csi.enabled  ( eq .Values.global.addons.csi.type "cinder-csi" ) -}}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: openstack-cinder-csi
spec:
  options:
    waitForJobs: true
    wait: true
    timeout: 30m0s
    install:
      createNamespace: true
  clusterSelector:
  # Target workload clusters with specific labels.
    matchLabels:
      csi.enabled: "true"
      csi.type: {{ .Values.global.addons.csi.type }}
      csi.version: {{ .Values.global.addons.csi.version }}
  # Target all workload clusters.
  #  matchLabels: {}
  releaseName: cinder-csi
  repoURL: https://kubernetes.github.io/cloud-provider-openstack
  chartName: openstack-cinder-csi
  version: {{ .Values.global.addons.csi.version }}
  namespace: kube-system
  valuesTemplate: |
    secret:
      enabled: true
      create: false
      name: cloud-config
    logVerbosityLevel: 4
    csi:
      provisioner:
        topology: "false"
        extraEnv:
          {{- if .Values.global.http_proxy }}
          - name: http_proxy
            value: {{ .Values.global.http_proxy | quote }}
          {{- end }}
          {{- if .Values.global.https_proxy }}
          - name: https_proxy
            value: {{ .Values.global.https_proxy | quote }}
          {{- end }}
          {{- if .Values.global.no_proxy }}
          # exclude from proxy pods.cidrBlocks, services.cidrBlocks
          - name: no_proxy
            value: "{{ .Values.global.no_proxy }},{{`{{ ( index .Cluster.spec.clusterNetwork.pods.cidrBlocks 0 ) }}`}},{{`{{ (index .Cluster.spec.clusterNetwork.services.cidrBlocks 0 ) }}`}},.svc,.svc.cluster,.svc.cluster.local,127.0.0.0/8,16,192.168.0.0/16"
          {{- end }}
      attacher:
        extraEnv:
          {{- if .Values.global.http_proxy }}
          - name: http_proxy
            value: {{ .Values.global.http_proxy | quote }}
          {{- end }}
          {{- if .Values.global.https_proxy }}
          - name: https_proxy
            value: {{ .Values.global.https_proxy | quote }}
          {{- end }}
          {{- if .Values.global.no_proxy }}
          # exclude from proxy pods.cidrBlocks, services.cidrBlocks
          - name: no_proxy
            value: "{{ .Values.global.no_proxy }},{{`{{ ( index .Cluster.spec.clusterNetwork.pods.cidrBlocks 0 ) }}`}},{{`{{ (index .Cluster.spec.clusterNetwork.services.cidrBlocks 0 ) }}`}},.svc,.svc.cluster,.svc.cluster.local,127.0.0.0/8,16,192.168.0.0/16"
          {{- end }}
      snapshotter:
        extraEnv:
          {{- if .Values.global.http_proxy }}
          - name: http_proxy
            value: {{ .Values.global.http_proxy | quote }}
          {{- end }}
          {{- if .Values.global.https_proxy }}
          - name: https_proxy
            value: {{ .Values.global.https_proxy | quote }}
          {{- end }}
          {{- if .Values.global.no_proxy }}
          # exclude from proxy pods.cidrBlocks, services.cidrBlocks
          - name: no_proxy
            value: "{{ .Values.global.no_proxy }},{{`{{ ( index .Cluster.spec.clusterNetwork.pods.cidrBlocks 0 ) }}`}},{{`{{ (index .Cluster.spec.clusterNetwork.services.cidrBlocks 0 ) }}`}},.svc,.svc.cluster,.svc.cluster.local,127.0.0.0/8,16,192.168.0.0/16"
          {{- end }}
      resizer:
        extraEnv:
          {{- if .Values.global.http_proxy }}
          - name: http_proxy
            value: {{ .Values.global.http_proxy | quote }}
          {{- end }}
          {{- if .Values.global.https_proxy }}
          - name: https_proxy
            value: {{ .Values.global.https_proxy | quote }}
          {{- end }}
          {{- if .Values.global.no_proxy }}
          # exclude from proxy pods.cidrBlocks, services.cidrBlocks
          - name: no_proxy
            value: "{{ .Values.global.no_proxy }},{{`{{ ( index .Cluster.spec.clusterNetwork.pods.cidrBlocks 0 ) }}`}},{{`{{ (index .Cluster.spec.clusterNetwork.services.cidrBlocks 0 ) }}`}},.svc,.svc.cluster,.svc.cluster.local,127.0.0.0/8,16,192.168.0.0/16"
          {{- end }}
      livenessprobe:
        extraEnv:
          {{- if .Values.global.http_proxy }}
          - name: http_proxy
            value: {{ .Values.global.http_proxy | quote }}
          {{- end }}
          {{- if .Values.global.https_proxy }}
          - name: https_proxy
            value: {{ .Values.global.https_proxy | quote }}
          {{- end }}
          {{- if .Values.global.no_proxy }}
          # exclude from proxy pods.cidrBlocks, services.cidrBlocks
          - name: no_proxy
            value: "{{ .Values.global.no_proxy }},{{`{{ ( index .Cluster.spec.clusterNetwork.pods.cidrBlocks 0 ) }}`}},{{`{{ (index .Cluster.spec.clusterNetwork.services.cidrBlocks 0 ) }}`}},.svc,.svc.cluster,.svc.cluster.local,127.0.0.0/8,16,192.168.0.0/16"
          {{- end }}
      nodeDriverRegistrar:
        extraEnv:
          {{- if .Values.global.http_proxy }}
          - name: http_proxy
            value: {{ .Values.global.http_proxy | quote }}
          {{- end }}
          {{- if .Values.global.https_proxy }}
          - name: https_proxy
            value: {{ .Values.global.https_proxy | quote }}
          {{- end }}
          {{- if .Values.global.no_proxy }}
          # exclude from proxy pods.cidrBlocks, services.cidrBlocks
          - name: no_proxy
            value: "{{ .Values.global.no_proxy }},{{`{{ ( index .Cluster.spec.clusterNetwork.pods.cidrBlocks 0 ) }}`}},{{`{{ (index .Cluster.spec.clusterNetwork.services.cidrBlocks 0 ) }}`}},.svc,.svc.cluster,.svc.cluster.local,127.0.0.0/8,16,192.168.0.0/16"
          {{- end }}
      plugin:
        extraEnv:
          {{- if .Values.global.http_proxy }}
          - name: http_proxy
            value: {{ .Values.global.http_proxy | quote }}
          {{- end }}
          {{- if .Values.global.https_proxy }}
          - name: https_proxy
            value: {{ .Values.global.https_proxy | quote }}
          {{- end }}
          {{- if .Values.global.no_proxy }}
          # exclude from proxy pods.cidrBlocks, services.cidrBlocks
          - name: no_proxy
            value: "{{ .Values.global.no_proxy }},{{`{{ ( index .Cluster.spec.clusterNetwork.pods.cidrBlocks 0 ) }}`}},{{`{{ (index .Cluster.spec.clusterNetwork.services.cidrBlocks 0 ) }}`}},.svc,.svc.cluster,.svc.cluster.local,127.0.0.0/8,16,192.168.0.0/16"
          {{- end }}

    storageClass:
      enabled: true
  # TODO: pay attention to newlines at the end that get inserted by templates
{{ end -}}
