provider:
  openstack: false
  outscale: false

global:
  # clusterName: cluster1-dev
  pods:
    cidrBlocks: "172.16.0.0/16"
  services:
    cidrBlocks: "10.96.0.0/12"
  # helmchartproxy installed inside workload cluster
  # helm addons
  addons:
    cni:
      enabled: true
      #type: calico
      #version: v3.27.3
      type: cilium
      version: 1.15.8
      config: {}
#        ipaddresspool:
#          layer: "l2"
#          name: "first-pool"
#          addresses:
#            - 192.168.101.11/32
    ccm:
      enabled: true
      #enabled: false
      type: openstack
      version: 2.31.0
    csi:
      enabled: true
      #enabled: false
      type: cinder-csi
      version: 2.31.0
    metallb:
      enabled: false
      type: metallb
      version: 0.14.5
      #config:
      #  ipaddresspool:
      #    layer: "l2"
      #    name: "first-pool"
      #    addresses:
      #      - 192.168.101.11/32
    ingress:
      enabled: false
      type: ingress-nginx
      version: 4.10.1
    certmanager:
      enabled: false
      type: cert-manager
      version: v1.14.5

#
# reference to openstack helm values
#
openstack: {}
#  machinehealthcheck:
#    enabled: false
#  sshkeyname: REPLACE_SSH_KEY_NAME_
#  router: router_services
#  network: network_kube
#  subnet: subnet_kube
#  bastion:
#    enabled: false
#    image: ubuntu22.04
#    flavor: CO1.2
#  controlplane:
#    version: v1.29.4
#    replicas: 1
#    image: ubuntu-2204-kube-v1.29.4
#    flavor: CO1.2
#    availabilityZones:
#      - AZ1
#      - AZ2
#    # reserved ip/port outside cluster-api
#    apiServerFixedIP: 192.168.101.10
#    #rootVolume: {}
#  workers:
#    md-0:
#      version: v1.29.4
#      replicas: 0
#      image: ubuntu-2204-kube-v1.29.4
#      flavor: CO1.2
#      # reserved ip/port outside cluster-api
#      ingressServerFixedIP: 192.168.101.11
#      #rootVolume: {}
##
## openstack cloud config
##
##  cloudConfig:
##    # used by ccm-openstack
##    cloudConf:
##      global:
##        auth-url: _OS_AUTH_URL/v3_
##        application-credential-id=_OS_APPLICATION_CREDENTIAL_ID_
##        application-credential-secret=_OS_APPLICATION_CREDENTIAL_SECRET_
##        region: "__OS_REGION_NAME_"
##    # used by cluster api provider openstack (capo)
##    cacert: _REPLACE_WITH_B64ENCODED_CACERT_
##    cloudsYaml: _REPLACE_WITH_B64_cloud.yaml_
#
##  dockerConfig:
#     registry: https://index.docker.io/v1/
#     auth: base64(docker_login:docker_password)
#
# reference to outscale helm values
#
outscale: {}
# sshkeyname: REPLACE_SSH_KEY_NAME_
# subregionName: "eu-west-2a"
# bastion:
#   enable: false
#   image: ubuntu-22.04-2204-kubernetes-v1.29.1-2024-02-19
#   rootDisk:
#     rootDiskIops: 100
#     rootDiskSize: 30
#     rootDiskType: standard
#   volumes:
#     - name: data-volume
#       size: 10
#       iops: 100
#       volumeType: standard
#       subregionName: eu-west-2a
# controlplane:
#   version: v1.29.5
#   replicas: 1
#   vmType: tinav5.c2r4p3
#   subregionName: "eu-west-2a"
# workers:
#   - name: md-0
#     version: v1.29.5
#     replicas: 0
#     vmType: tinav5.c2r4p3
#     subregionName: "eu-west-2a"
#     image: ubuntu-22.04-2204-kubernetes-v1.29.1-2024-02-19
#     rootDisk:
#       rootDiskIops: 100
#       rootDiskSize: 30
#       rootDiskType: standard
#  osc_credentials:
#    secret_key: ""
#    access_key: ""
#    region: ""
#
##  dockerConfig:
#     registry: https://index.docker.io/v1/
#     auth: base64(docker_login:docker_password)
