---
apiVersion: v1
kind: Secret
type: addons.cluster.x-k8s.io/resource-set
metadata:
  annotations:
    note: generated
    #"helm.sh/resource-policy": "keep"
    ## install first, and delete at the end
    "helm.sh/hook": "pre-install,post-delete"
    "helm.sh/hook-weight": "-1"
    # For Argo, this resource should be pruned last out of everything
    argocd.argoproj.io/sync-options: PruneLast=true
  labels:
    type: generated
  name: {{ .Values.global.clusterName }}-ccm-outscale-config
  namespace: default
stringData:
  OscCloudConf: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: osc-secret
      namespace: kube-system
    stringData:
      key_id: {{ .Values.osc_credentials.access_key }}
      access_key: {{ .Values.osc_credentials.secret_key }}
      aws_default_region: {{ .Values.osc_credentials.region }}
      aws_availability_zones: MY_AWS_AVAILABILITY_ZONES
      osc_account_id: MY_OSC_ACCOUNT_ID
      osc_account_iam: MY_OSC_ACCOUNT_IAM
      osc_user_id: MY_OSC_USER_ID
      osc_arn: MY_OSC_ARN
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ .Values.global.clusterName }}-ccm-outscale-config
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  resources:
  - kind: Secret
    name: {{ .Values.global.clusterName }}-ccm-outscale-config
  strategy: Reconcile
