apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscMachineTemplate
metadata:
  name: {{ .Values.global.clusterName }}-control-plane-{{ .Values.controlplane.version }}
spec:
  template:
    spec:
      node:
        clusterName: {{ .Values.global.clusterName }}
        image:
          name: {{ .Values.controlplane.image }}
        keypair:
          name: {{ .Values.sshkeyname }}
          deleteKeypair: false
        vm:
          clusterName: {{ .Values.global.clusterName }}
          keypairName: {{ .Values.sshkeyname }}
          loadBalancerName: {{ .Values.loadbalancername | default "{{ .Values.global.clusterName }}-k8s" }}
          role: controlplane
          vmType: {{ .Values.controlplane.vmType }}
          subregionName: {{ .Values.controlplane.subregionName  }}
          {{- if hasKey .Values.controlplane "rootDisk" }}
          rootDisk:
            rootDiskIops: {{ .Values.controlplane.rootDisk.rootDiskIops | default 100 }}
            rootDiskSize: {{ .Values.controlplane.rootDisk.rootDiskSize | default 30 }}
            rootDiskType: {{ .Values.controlplane.rootDisk.rootDiskType | default "standard" }}
          {{- end }}
        {{- with .Values.controlplane.volumes }}
        volumes: {{- toYaml . | nindent 10 }}
        {{- end }}
